<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Edit a survey item.
 *
 * @package     block_coursefeedback
 * @copyright   2025 innoCampus, Technische Universität Berlin
 * @copyright   2025 Moodle.NRW, Ruhr-Universität Bochum
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

use block_coursefeedback\local\manager\breadcrumbs_manager;
use block_coursefeedback\local\manager\permission_manager;
use block_coursefeedback\local\multilang_string;
use block_coursefeedback\local\persistent\surveyitem;
use block_coursefeedback\local\persistent\surveypart;
use block_coursefeedback\local\surveyitem\surveyitem_form;
use block_coursefeedback\local\surveyitem\surveyitem_manager;

require_once(__DIR__ . '/../../config.php');
global $CFG, $DB, $OUTPUT, $PAGE;

/**
 * Turns the form data generated by multiple editors into a {@see multilang_string} and their format.
 *
 * This function also checks that all the editors are using the same format.
 *
 * @param array<string, object> $editors
 * @param string[] $languages
 * @return array{multilang_string, int}|null The constructed multilang string and the format.
 * @throws moodle_exception If the editors use different formats.
 * @throws coding_exception If the data is invalid in another way.
 */
function editors_to_multilang_string(array $editors, array $languages): ?array {
    $translations = [];
    $first_format = null;

    foreach ($editors as $language => $editor) {
        if (!is_string($language) || !is_array($editor)) {
            throw new coding_exception('Invalid editor data.');
        }

        if (!in_array($language, $languages)) {
            continue;
        }

        $format = $editor['format'] ?? FORMAT_PLAIN;
        if (!is_number($format)) {
            throw new coding_exception("Invalid editor format: '$format'");
        }
        $format = intval($format);
        if ($first_format === null) {
            $first_format = $format;
        } else if ($first_format !== $format) {
            // Should've been caught by form validation.
            throw new moodle_exception('inconsistent_editor_formats', 'block_coursefeedback');
        }

        $translations[$language] = $editor['text'];
    }

    $text = multilang_string::from_array($translations);
    return $text ? [$text, $first_format] : null;
}

require_login();

$id = optional_param('id', null, PARAM_INT);
$surveypartid = required_param('surveypartid', PARAM_INT);
$surveypart = surveypart::get_record(['id' => $surveypartid], MUST_EXIST);

permission_manager::require_permission_for_editing_surveypart($surveypart);

$type = required_param('type', PARAM_ALPHANUMEXT);
$surveyitemtype = surveyitem_manager::get_surveyitemtype($type);

$params = ['surveypartid' => $surveypartid, 'type' => $type];

$surveyitem = null;
if ($id) {
    $params['id'] = $id;
    $surveyitem = surveyitem::get_record(['id' => $id], MUST_EXIST);
    if ($surveyitem->get('surveypartid') !== $surveypartid || $surveyitem->get('surveyitemtype') !== $type) {
        // Generic error message.
        throw new coding_exception('Could not load surveyitem');
    }
}

$PAGE->set_url(new moodle_url('/blocks/coursefeedback/surveyitem_edit.php', $params));
if ($id) {
    $title = get_string('edit_surveyitem', 'block_coursefeedback');
} else {
    $title = get_string('new_surveyitem', 'block_coursefeedback');
}

$PAGE->set_context(context_system::instance());
$PAGE->set_heading($title);
$PAGE->set_title($title);
breadcrumbs_manager::setup_edit_surveyitem($surveypart, $surveyitem);

$returnurl = new moodle_url('/blocks/coursefeedback/surveypart.php', ['id' => $surveypartid]);

$mformclass = $surveyitemtype->get_settings_mform();

if (!$mformclass) {
    if ($id) {
        throw new coding_exception('Cannot edit item of type ' . $type);
    }

    require_sesskey();
    $sortindex = surveyitem::count_records(['surveypartid' => $surveypartid]);
    $surveyitem = new surveyitem();
    $surveyitem->set('surveypartid', $surveypartid);
    $surveyitem->set('surveyitemtype', $type);
    $surveyitem->set('sortindex', $sortindex);
    $surveyitem->save();
    redirect($returnurl);
}

/** @var surveyitem_form $mform */
$mform = new $mformclass($PAGE->url, $surveypart);

if ($surveyitem) {
    $data = $surveyitemtype->load_settings_mform($surveyitem);
    $mform->set_data($data);
}

if ($mform->is_cancelled()) {
    redirect($returnurl);
} else if (($data = $mform->get_data()) && !$mform->no_submit_button_pressed()) {
    if (!$surveyitem) {
        $sortindex = surveyitem::count_records(['surveypartid' => $surveypartid]);
        $surveyitem = new surveyitem();
        $surveyitem->set('surveypartid', $surveypartid);
        $surveyitem->set('surveyitemtype', $type);
        $surveyitem->set('sortindex', $sortindex);
    }

    if (isset($data->text)) {
        [$text, $textformat] = editors_to_multilang_string($data->text, $surveypart->get_languages());
        $surveyitem->set('text', $text);
        $surveyitem->set('textformat', $textformat);
    }

    $surveyitem->save();
    $surveyitemtype->save_settings_mform($surveyitem, $surveypart, $data);
    redirect($returnurl);
} // Else display form.

echo $OUTPUT->header();

$mform->display();

echo $OUTPUT->footer();
