<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

namespace block_coursefeedback\local;

use block_coursefeedback\local\persistent\response_slot;
use block_coursefeedback\local\persistent\survey_execution;
use block_coursefeedback\local\persistent\survey_part_execution;
use block_coursefeedback\local\persistent\surveypart;
use block_coursefeedback\local\surveyitem\surveyitem_manager;

/**
 * A class containing all the data needed to display a survey.
 *
 * @package     block_coursefeedback
 * @copyright   2026 innoCampus, Technische Universität Berlin
 * @copyright   2026 Moodle.NRW, Ruhr-Universität Bochum
 * @license     https://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */
class survey {

    /**
     * Private constructor.
     *
     * @param survey_execution $survey_execution
     * @param survey_page[] $pages
     * @param array<int, response_slot[]> $slots_by_spe_id
     */
    private function __construct(
        /** @var survey_execution $survey_execution */
        public readonly survey_execution $survey_execution,
        /** @var survey_page[] $pages */
        public readonly array $pages,
        /** @var array<int, response_slot[]> $slots_by_spe_id */
        public readonly array $slots_by_spe_id,
    ) {
    }

    /**
     * Create an instance to display the survey for the given course.
     *
     * @param survey_execution_data $course_data
     * @return self
     */
    public static function for_course(survey_execution_data $course_data): self {
        $events_by_spe_id = [];
        foreach ($course_data->spes_by_event_id as $event_id => $spe) {
            $events_by_spe_id[$spe->get('id')] = $course_data->events_by_id[$event_id];
        }

        foreach ($course_data->spes_by_event_id as $spe) {
            // Sanity check: Does the survey execution data contain all necessary survey parts?
            if ($spe->get('surveypartid') && !isset($course_data->survey_parts_by_spe_id[$spe->get('id')])) {
                debugging(
                    "Survey part '{$spe->get('surveypartid')}' referenced by survey part execution '{$spe->get('id')}' " .
                    "has not been loaded."
                );
            }
        }

        $pages = surveyitem_manager::export_pages_for_survey(
            surveyparts: array_values($course_data->survey_parts_by_spe_id),
            spes: array_values($course_data->spes_by_event_id),
            events_by_spe_id: $events_by_spe_id,
            slots_by_spe_id: $course_data->slots_by_spe_id
        );

        return new self(
            $course_data->survey_execution,
            $pages,
            $course_data->slots_by_spe_id,
        );
    }

    /**
     * Create an instance only showing the given surveypart so that users may test it.
     *
     * There is no association to a course and answers will never be saved.
     *
     * @param surveypart $surveypart
     * @return self
     */
    public static function for_testing_surveypart(surveypart $surveypart): self {
        $se = (new survey_execution())->set_many([
            "id" => -1,
            "courseid" => -1,
            "organizationid" => $surveypart->get('organizationid') ?: -1,
            "status" => survey_execution::STATUS_STARTED,
        ]);

        // Negative IDs prevent accidentally saving the SE, SPE or slot.
        $spe = (new survey_part_execution())->set_many([
            "id" => -1,
            "surveyexecutionid" => -1,
            "surveypartid" => $surveypart->get('id'),
        ]);
        $slots = [
            $spe->get('id') => [
                (new response_slot())->set_many([
                    "id" => -1,
                    "surveypartexecutionid" => $spe->get('id'),
                    "name" => "-",
                ]),
            ],
        ];

        $pages = surveyitem_manager::export_pages_for_survey(
            surveyparts: [$surveypart],
            spes: [$spe],
            events_by_spe_id: [],
            slots_by_spe_id: $slots
        );

        return new self($se, $pages, $slots);
    }

    /**
     * Check if this survey is empty. A survey is considered empty if it has no pages or all pages are empty.
     *
     * @return bool
     */
    public function is_empty(): bool {
        // TODO: Also consider a survey empty when all items are autogenerated.
        // Or maybe don't add those if there are no proper items.
        return !array_filter($this->pages, fn($page) => !empty($page->items));
    }
}
